config/routes.rb
Rails.application.routes.draw do

  root 'genres#index'
  resources :users do
    resources :ratings, except: [:index]
  end

  resources :genres
  resources :artists
  resources :reviews
  resources :comments

  get 'logout' => 'sessions#destroy'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'

end

app/models/genre.rb
class Genre < ActiveRecord::Base

  validates :name, uniqueness: true, presence: true

  has_many :artist_genres
  has_many :artists, through: :artist_genres

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  def index
    @genres = Genre.all
  end

  def show
    genre = Genre.find(params[:id])
    @users = genre.artists
    render 'show_genre'
  end

end

app/views/genres/index.html.erb
<!-- Display the genres... would like to display in a pretty grid format -->

<% if flash[:notice] %>
  <%# Leave alignment to your CSS. Do not use the center tag. %>
  <center><%= flash[:notice] %></center>
  <% flash[:notice] = nil %>
<% end %>

<ul class="rig columns-3">
  <% @genres.each do |genre| %>
    <%= link_to genre_path(genre, genre.name) do %>
        <li>
          <h2><center><%= genre.name %></center></h2>
          <img src = "<%= genre.image_url %>">
        </li>
    <% end %>
  <% end %>
</ul>

app/views/genres/show_genre.html.erb
<div ><h1>Artists</h1></div>
<% @users.each do |user| %>
  <li>
    <div class="well well-lg">
      <%# No need to interpolate here. %>
      <h2><%= link_to "#{user.first_name}", user %></h2>
    </div>
  </li>
<% end %>