config/routes.rb
Rails.application.routes.draw do

  root 'genres#index'
  resources :users do
    resources :ratings, except: [:index]
  end

  resources :genres
  resources :artists
  resources :reviews
  resources :comments

  get 'logout' => 'sessions#destroy'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  validates   :body, presence: true
  validates   :commenter, presence: true
  validates   :review, presence: true
  
  belongs_to  :commenter, class_name: "User"
  belongs_to  :review

  has_many    :ratings, as: :ratingable

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def show
    # Typos :(
    @comment = Comment.find(params[:id])
  end

  def new
    # There shouldn't be any need for params at this point.
    @comment = Comment.new(params[:comment])
  end

  def create
    @comment = Comment.new(comment_params)
    # Why aren't you permitting review_id & commenter_id, which would
    # eradicate the need for the following two lines?
    @comment.review = Review.find(params[:comment][:review_id])
    @comment.commenter = User.find(params[:comment][:commenter_id])
    @comment.save
    @user = @comment.review.artist
    redirect_to("/users/#{@user.id}")
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end

end

app/views/comments/_form.html.erb
<%= form_for :comment, url: comments_path do |f| %>
<%# Don't leave debugging code in master / your app / your views %>
<h1><%= puts params %></h1>
  <div class="comment-box">
    <%= f.label :comment %><br>
    <%= f.text_area :body %><br>
    <%= f.hidden_field :review_id, { :value => params[:format] } %>
    <%= f.hidden_field :commenter_id, { :value => session[:user_id] } %>
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/new.html.erb
<h1 id="comment-tag">New comment</h1>
<%= render 'form' %>

app/views/comments/show.html.erb
<%# Don't commit empty files. %>