config/routes.rb
Rails.application.routes.draw do

  root 'genres#index'
  resources :users do
    resources :ratings, except: [:index]
  end

  resources :genres
  resources :artists
  resources :reviews
  resources :comments

  get 'logout' => 'sessions#destroy'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.where(artist: @user.id)
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new(params[:review])
  end

  def create
    @review = Review.new(review_params)
    @review.artist = User.find(params[:review][:artist_id])
    @review.reviewer = User.find(params[:review][:reviewer_id])
    @review.save
    redirect_to(:back)
  end

  def update
    @review = Review.find(params[:id])
    @user = @review.artist

    if @review.update(review_params)
      redirect_to "/users/#{@user.id}"
    else
      render 'edit'
    end
  end

  def edit
    @review = Review.find(params[:id])

  end

  def destroy
    @review = Review.find(params[:id])
    @user = @review.artist
    @review.destroy
    respond_to do |format|
      format.js do
        render nothing: true
      end
      format.any do
      redirect_to "/users/#{@user.id}"
      end
    end
  end


  private
    def review_params
      params.require(:review).permit(:body)
    end
end

app/views/reviews/_form.html.erb
<%= form_for :review, remote: true, url: reviews_path do |f| %>
   <p>
    <%= f.label :review %><br>
    <%= f.text_area :body %><br>
    <%= f.hidden_field :artist_id, { :value => @user.id } %>
    <%= f.hidden_field :reviewer_id, { :value => session[:user_id] } %>
    <%= f.submit %>  </p>

<% end %>

app/views/reviews/_index.html.erb
<h1>Reviews on <%= @user.full_name %> </h1>
  <% @user.reviews_as_artist.each do |review| %>
      <blockquote>
      <p><%= review.body %></p>
      <small><%= review.reviewer.first_name %><cite title="Source Title">(<%= review.reviewer.username %>)</cite></small>
      </blockquote>
    <%= link_to 'Comment', new_comment_path(review) %>
    <%= link_to 'Edit', edit_review_path(review) %>
    <%= link_to 'Delete', review_path(review), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% review.comments.each do |comment| %>
      <blockquote class="review-comment-quote">
      <p><%= comment.body %></p>
      <small><%= comment.commenter.first_name %><cite title="Source Title">(<%= comment.commenter.username %>)</cite></small>
      </blockquote>
      <% end %>
  <% end %>

app/views/reviews/edit.html.erb
<h1 id="review-tag">Edit review</h1>

<%# Place your form inside your div, not the other way around. %>
<%= form_for :review, url: review_path(@review), method: :patch do |f| %>
 <div class="review-box">
    <%= f.label :review %><br>
    <%= f.text_area :body %><br>
    <%= f.submit %>
 </div>
<% end %>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= render 'form' %>

<%= link_to 'Go Back', reviews_path %>